### ISSUE TITLE
Provide a way to have approval via invoking a Lambda function workflow

### ISSUE THREAD

**Issue by alFReD-NSH** [awslabs/serverless-transit-network-orchestrator#13]
We want to approve any VPC who's CIDR is registered in our IPAM system and have a certain tag. We would like to approve any VPC in our organisation but in case someone tries to attach a VPC with a CIDR that don't belong to them, this might ruin connectivity for some other teams and we would like to avoid this.

**Comment by groverlalit** [comment]
@alFReD-NSH 
The auto-approve vs approval workflow is solely depends on the tag on the TGW route table. The solution workflow is not cognizant of VPC properties. 
Should we need add a mechanism to block the user to create a VPC with a CIDR that doen not belong to them?

**Comment by alFReD-NSH** [comment]
Hi,

> Should we need add a mechanism to block the user to create a VPC

Actually that gave me an idea on how to do this for our organization via tags and SCPs which I think is a better way

Thanks for the help, I'm gonna close this since there's a better way for us.
