### ISSUE TITLE
manifest-generator: No such file or directory

### ISSUE THREAD

**Issue by maheshrayas** [awslabs/serverless-transit-network-orchestrator#14]
Description:
I am trying to make some changes to code(custom_resource_handler.py) and trying to build. I get below error when its trying to generate the console-manifest.json

`./build-s3-dist.sh: line 99: cd: /Users/<>/<>/repo/serverless-transit-network-orchestrator/deployment/manifest-generator: No such file or directory `

and due to above issue,
`cd /Users/<>/<>/repo/serverless-transit-network-orchestrator/deployment/regional-s3-assets && zip -rv ./aws-transit-network-orchestrator-cr.zip ./console-manifest.json
	zip warning: name not matched: ./console-manifest.json
`

and the final package aws-transit-network-orchestrator-cr.zip doesn't contain the console-manifest.json.

Can you please suggest if I am doing anything wrong.

**Comment by aijunpeng** [comment]
Thanks for reporting the issue. It seems manifest-generator is missing from the GitHub open source. We have added the issue to our backlog and will have it fixed in near future.

**Comment by rakshb** [comment]
@maheshrayas Hello! we have fixed this and pushed the manifest-generator folder to GitHub repo

**Comment by maykays** [comment]
Resolved. Closing issue.
